# Generated by Django 4.0 on 2023-12-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
