# Generated by Django 4.0 on 2023-12-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
