# Generated by Django 4.0 on 2023-12-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_confirmationcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
